force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Intake__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/S3_Key__c.field-meta.xml
<CustomField>
    <fullName>S3_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>S3 Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Intake__c/Intake__c.object-meta.xml
<CustomObject>
    <label>Intake</label>
    <nameField>
        <displayFormat>INT-{YYYY}-{00000}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/S3PresignedUrlService.cls
public with sharing class S3PresignedUrlService {
    @AuraEnabled
    public static String getUploadUrl(String fileName, Id intakeId) {
        String key = 'Intake/' + intakeId + '/' + fileName;

        HttpRequest req = new HttpRequest();
        req.setEndpoint(
            'https://fpxbao3eq1.execute-api.us-east-1.amazonaws.com/prod/upload-url?key=' +
            EncodingUtil.urlEncode(key, 'UTF-8')
        );
        req.setMethod('GET');

        Http http = new Http();
        HttpResponse res = http.send(req);

        System.debug(res.getBody());

        return res.getBody();
    }

    @AuraEnabled
    public static String createDocument(String fileName, String s3Key, Id intakeId) {
        String fileUrl = 'https://legal-intake-documents.s3.amazonaws.com/' + s3Key;

        Document__c doc = new Document__c(
            Name = fileName,
            File_URL__c = fileUrl,
            S3_Key__c = s3Key,
            Intake__c = intakeId
        );

        insert doc;
        return fileUrl;
    }
}